/var/log/paodo/app.log /var/log/paodo/credproxy.log /var/log/paodo/security.log {
    daily
    maxsize 50M
    rotate 14
    missingok
    notifempty
    compress
    copytruncate
    nocreate
    su 1000 1000
}
