// The one ignore contract every file transfer honours, in both directions.
//
// Before this module there were three answers to "what travels": the file tree hid one set of names
// (.git, the Python caches), a folder upload left out a different set (node_modules, .venv, the
// framework build dirs), and the download zip filtered nothing at all. That is survivable while the
// only client is a UI where each surface is looked at on its own, but a push/pull pair built on
// three different answers drifts on every round trip: you pull a tree that omits .git, push it back,
// and a mirroring push then wants to delete files it was never shown. So the contract is defined
// once, here, and every walker, archiver and uploader reads it — which is also what makes it
// serveable, so a client can ask what the effective contract is instead of hardcoding a copy.
//
// The bar for adding a name is deliberately narrow: a fixed, tool-owned convention name — one no
// project would plausibly reuse for hand-authored content — that's quickly regenerated in place
// (npm install, pip install, ./gradlew, ...) or, if the toolchain isn't already in the workspace,
// installable by the agent first via apt_install. Kept out deliberately: plain-English names
// ("target", "bin", "obj", "build", "dist", "cache", "out", ...) that some ecosystem uses as a build
// convention but that plenty of other projects also use for genuinely hand-authored content (a
// repo's own `bin/` of maintained scripts, a "target" folder of business documents, ...) — excluding
// those by default risks silently dropping what the user meant to transfer, which is worse than the
// problem this list exists to solve.
//
// Keep this module free of server-only imports (no fs, no path) — same convention as limits.ts,
// since the upload preview UI needs the contract as much as the server walkers do. The server-side
// directory reader that applies it lives in ./entries.ts.

/** Regenerated by a tool, never hand-authored. Excluded in both directions. */
export const REGENERATED_DIR_NAMES: readonly string[] = [
  "node_modules", // JS/TS — npm/yarn/pnpm install
  "__pycache__", // Python bytecode cache — recreated the moment .py files run
  ".venv",
  "venv", // Python virtualenvs — python3 -m venv + pip install
  ".next",
  ".nuxt",
  ".svelte-kit",
  ".angular", // framework build output — dotted, framework-owned, never hand-authored
  ".turbo",
  ".parcel-cache", // build-tool caches — same reasoning
  ".pytest_cache",
  ".mypy_cache",
  ".ruff_cache",
  ".tox", // Python tooling caches
  ".gradle", // Gradle's own cache dir — the project's own gradlew wrapper fetches Gradle itself
];

/**
 * The agent's own repository inside the workspace, if it ran `git init` there. Ours is elsewhere
 * (<root>/.versioning/<id>, see workspaceVersioning.ts), so this is never our snapshot history.
 *
 * It does not travel, and that is the deliberate answer to "does .git travel": the file tree has
 * always hidden it, so today you can upload a .git you then cannot see — and a transfer that carried
 * it would move an object store file-by-file, where a half-applied push leaves a corrupt repo rather
 * than a merely incomplete tree. A workspace's history is reachable through the snapshot/restore
 * operations instead. Flipping this is one line, and both directions change together.
 */
export const VCS_DIR_NAMES: readonly string[] = [".git"];

/** The effective directory-name contract. Matched on whole path segments only. */
export const IGNORED_DIR_NAMES: readonly string[] = [...REGENERATED_DIR_NAMES, ...VCS_DIR_NAMES];

/**
 * File suffixes excluded wherever they appear. Only ever compiled output whose source sits beside
 * it; the directory rules above already cover the common case (`__pycache__`), so this exists for
 * the strays that older Python versions leave next to their `.py`.
 */
export const IGNORED_FILE_SUFFIXES: readonly string[] = [".pyc", ".pyo"];

/** The contract as one value — what a "serve the effective contract" endpoint would return. */
export interface IgnoreContract {
  dirNames: readonly string[];
  fileSuffixes: readonly string[];
}

export const IGNORE_CONTRACT: IgnoreContract = {
  dirNames: IGNORED_DIR_NAMES,
  fileSuffixes: IGNORED_FILE_SUFFIXES,
};

/**
 * Whether a single directory entry is excluded, given its own name and whether it is a directory.
 * This is the primitive a directory walker applies as it descends; `partitionByIgnore` below is the
 * same contract applied to a flat list of already-known relative paths.
 *
 * Returns the matched rule rather than a bare boolean so callers can say *which* rule excluded an
 * entry — that is what lets the upload summary read "node_modules excluded (14,200 files)".
 */
export function ignoreRuleFor(
  name: string,
  isDirectory: boolean,
  contract: IgnoreContract = IGNORE_CONTRACT,
): string | undefined {
  if (isDirectory) return contract.dirNames.includes(name) ? name : undefined;
  return contract.fileSuffixes.find((suffix) => name.endsWith(suffix));
}

export interface IgnorePartition<T> {
  included: T[];
  /** Matched rule (an ignored directory name, or a file suffix) -> the entries it excluded. */
  excluded: Map<string, T[]>;
}

/**
 * Split `entries` into what a transfer should send and what it should leave out, based on
 * `entry.path`. Directory rules match whole path segments only — so "my-node_modules-notes.txt" is
 * never mistaken for the node_modules directory — and only against segments that really are
 * directories here (the last segment is the file itself). The file-suffix rules apply to that last
 * segment.
 */
export function partitionByIgnore<T extends { path: string }>(
  entries: T[],
  contract: IgnoreContract = IGNORE_CONTRACT,
): IgnorePartition<T> {
  const included: T[] = [];
  const excluded = new Map<string, T[]>();

  for (const entry of entries) {
    const segments = entry.path.split("/");
    const fileName = segments[segments.length - 1];
    const matched =
      segments.slice(0, -1).find((segment) => ignoreRuleFor(segment, true, contract) !== undefined) ??
      ignoreRuleFor(fileName, false, contract);
    if (matched === undefined) {
      included.push(entry);
      continue;
    }
    const bucket = excluded.get(matched) ?? [];
    bucket.push(entry);
    excluded.set(matched, bucket);
  }

  return { included, excluded };
}
